development:
  adapter: postgresql
  encoding: unicode
  database: taxi-dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: taxi-test
  pool: 5

production:
  host: db.fasttaxi.com.br
  adapter: postgresql
  database: taxi-prod
  prepared_statements: false
  username: fasttaxi
  password: j6N48t2YpxfDRad4
  pool: 5
