production:
  host: redis.taxifinder.com.br
  port: 6379
  database: 0
  password: LhT2xrfgSUapCrbJ8qVL3EYy9vwfZ8dfuBcrfXL3h7q769fc6nYwnHz8ukDmRga3cBXH56PzEj5k2h5K8a6T2tL2EcZQNTvK3aSeYn3HBFTrd95Kk3YX3jeY2y39W9WnxPAyT543H6Qaf2VmqqPa2sggXu2CVtMRXVjXxzvC6w3nMvpPYg2CQe3rwpbftrg3Jr92BqgrRyyXHJqAzUceAyDPRv2za7d8rp9NXYczQ7NBR7Yp69S8D9WZHVVRgLSh
development:
  host: localhost
  port: 6379
  database: 0
test:
  host: localhost
  port: 6379
  database: 0
